language: elixir
elixir:
  - 1.7
otp_release:
  - 21.0
services:
  - postgresql
env:
  global:
    - MIX_ENV=test
before_script:
  - psql -c 'create database soft_repo_test;' -U postgres
script:
  - mix test
